# Generated by Django 2.1.2 on 2018-10-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlentry',
            name='origin_url',
        ),
    ]
