# Generated by Django 2.1.2 on 2018-10-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlentry',
            name='friendly_key',
            field=models.IntegerField(default=0),
        ),
    ]
