# Generated by Django 2.1.2 on 2018-10-25 08:22

from django.db import migrations, models
import shorturls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0002_remove_urlentry_origin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlentry',
            name='friendly_name',
            field=models.CharField(error_messages={'unique': 'This friendly name is unavailabe.'}, help_text='Type in a friendly name you would like to use and we will check if it is available', max_length=128, validators=[shorturls.validators.FriendValidator]),
        ),
    ]
